SELECT
  "id"::INT,
  "Name" AS "name",
  "Release_Date"::DATE AS "release_date",
  "IMDB_URL" AS "imdb_url",
  "War"::INT::BOOLEAN,
  "Crime"::INT::BOOLEAN,
  "Drama"::INT::BOOLEAN,
  "Action"::INT::BOOLEAN AS "action",
  "Comedy"::INT::BOOLEAN,
  "Horror"::INT::BOOLEAN,
  "Sci_Fi"::INT::BOOLEAN AS "sci_fi",
  "Fantasy"::INT::BOOLEAN,
  "Musical"::INT::BOOLEAN,
  "Mystery"::INT::BOOLEAN,
  "Romance"::INT::BOOLEAN,
  "Western"::INT::BOOLEAN,
  "unknown"::INT::BOOLEAN,
  "Thriller"::INT::BOOLEAN,
  "Adventure"::INT::BOOLEAN,
  "Animation"::INT::BOOLEAN,
  "Film_Noir"::INT::BOOLEAN AS "film_noir",
  "Children_s"::INT::BOOLEAN AS "childrens",
  "Documentary"::INT::BOOLEAN
FROM {{ source('raw_data', 'movies') }}
